services:
  postgres:
    image: postgres:15
    container_name: price-tracker-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dk212dFehd
      POSTGRES_DB: PriceTracker.OzonDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: price-tracker-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: dk212dFehd
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  rabbitmq:
    image: rabbitmq:management           
    container_name: price-tracker-queue
    environment:
      RABBITMQ_DEFAULT_USER: admin       
      RABBITMQ_DEFAULT_PASS: dk212dFehd  
    ports:
      - "5672:5672"                       
      - "15672:15672"                      
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq    
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  # =================================

volumes:
  postgres_data:
  pgadmin_data:
  rabbitmq_data:  